<?php
/**
 * Created by PhpStorm.
 * User: Andrei
 * Date: 01.08.2017
 * Time: 16:38
 */

namespace App\Models;
use App\Exceptions\MultiException;

/**
 * Class News
 * @package App\Models
 * @property \App\Models\Author $author
 */

class News
	extends Model
{
	protected $data = [];
	
	public function __set($name, $value)
	{
		// TODO: Implement __set() method.
		if ('author' == $name) {
			$author = Author::findByID($this->author_id);
			if (empty($author)) {
				$author = new Author();
				$author->name = $value;
				$author->save();
				$author->id = $author->lastId();
			} else {
				$author->name = $value;
				$author->save();
			}
			$$name = $author->id;
//			var_dump($$name);die;
			return $$name;
		}
	}
	
	/**
	 * LAZY LOAD
	 *
	 * @param $name
	 * @return null|object
	 */
	public function __get($name)
	{
		// TODO: Implement __get() method.		
		if ('author' == $name) {
			return Author::findByID($this->author_id);
		}
		return null;
	}
	
	public function __isset($name)
	{
		// TODO: Implement __set() method.
		if ('author' == $name) {
//			$id = Author::findByID($this->author_id);
			return !empty($this->author_id);
		}
		return false;
	}
	
	const TABLE = 'news';
	public $id;
	public $title;
	public $text;
	public $author_id;
	
	public function getArticleById($id)
	{
		$res = parent::findByID($id);
		return $res;
	}
	
	public function insert()
	{
		parent::insert(); // TODO: Change the autogenerated stub
		
	}
	
	public function fill($data = [])
	{
		$e = new \App\Exceptions\MultiException();
		if(true){
			$e[] = new \Exception('Titlu incorect');
		}if(true){
			$e[] = new \Exception('Text incorect');
		}
		throw $e;
	}
}
